frontend:
  image: jheyuliu/frontend
  tag: f8b8b97
  autoscaling:
    averageUtilization: 60

backend:
  image: jheyuliu/backend
  tag: f8b8b97
  autoscaling:
    averageUtilization: 60

database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
